name: ViewSlimeChunk
version: '1.1.1'
main: top.e404.viewslimechunk.Main
api-version: '1.21'
folia-supported: true
java-version: 21
authors: [ 404E ]
commands:
  slime:
    description: "插件主命令"
  slimereload:
    description: "重载插件"
permissions:
  viewslimechunk.use:
    default: op
  viewslimechunk.admin:
    default: op
